### ISSUE TITLE
Unexpected drag behavior of the OpenLayer map in FB WebView

### ISSUE THREAD

**Issue by tpai** [kiang/pharmacies#1]
**Reproduce**
1. Click the pharmacies map link in any post of Facebook timeline.
1. A WebView opened.
1. Try to drag down inside the map.
1. The drag event looks went through the map and the WebView is going to close.

**Expected Result**
The dragging of the map works fine, and no effect on the WebView.

**Demo**
![pharmacies-map-demo](https://media.giphy.com/media/l3OYzDNv5WxVlXG0OZ/giphy.gif)

**Comment by tpai** [comment]
@kiang It looks like the issue is from OpenLayer library, I tried to do the same thing at the map from their website, it also happened.

![openlayer-map-demo](https://media.giphy.com/media/eHA7WuVwrzoeE7uAul/giphy.gif)

**Comment by kiang** [comment]
Yes, it looked like an upstream issue. I'm not that familiar with the core source. Maybe you could report it at https://github.com/openlayers/openlayers/issues ?

**Comment by tpai** [comment]
Sure thanks.
