### ISSUE TITLE
沒這家藥局

### ISSUE THREAD

**Issue by openegret** [kiang/pharmacies#11]
我的家鄉不存在的藥局,請更正  https://kiang.github.io/pharmacies/#5940131381
沒這家藥局

**Comment by kiang** [comment]
點過去官方網站看 3/5 還有更新資料耶？
http://www.nhi.gov.tw/QueryN/Query3_Detail.aspx?HospID=5940131381

**Comment by openegret** [comment]
怪怪?我當時在現場來回走來走去看,就是沒這家,現己回到台北,開Google街景,是二家完全不同的診所,我不知問題出在那

**Comment by kiang** [comment]
或許是登記地址跟實際營業地址不同，但我基本上都用官方資料去處理

**Comment by openegret** [comment]
感謝您,
我當時一看庫存量,就立時騎機車到現場想買,左看右看來回騎,就完全沒這家,
今一看,它庫存量還4千多片.
想,不回報不行了.
還是感謝您的付出

**Comment by kiang** [comment]
研究了一下，頂六藥局(３４之６５號)就在蔡元慶診所(３４之６３號)隔壁，猜測會不會是共同營業所以沒有獨立的看板與對外識別，如果有機會可以問問蔡元慶診所看看
