### ISSUE TITLE
住家附近三間藥局沒在地圖裏

### ISSUE THREAD

**Issue by jodie0925** [kiang/pharmacies#12]
住家附近三間藥局沒在地圖裏：
**品誼藥局**
地址： 812高雄市小港區平和路22號
電話： 07 821 9527

**龍祺藥局**
地址：812高雄市小港區平和路111號
電話： 07 831 5352

**大裕藥局**
地址： 812高雄市小港區小港路261號
電話： 07 821 1467

**Comment by kiang** [comment]
品誼藥局 - https://kiang.github.io/pharmacies/#5907380077
龍祺藥局 - https://kiang.github.io/pharmacies/#5902110431
大裕藥局 - https://kiang.github.io/pharmacies/#5902110299

看起來都有，也許是位置錯誤？

**Comment by jodie0925** [comment]
沒問題了…謝謝您的回覆^^
