### ISSUE TITLE
回報藥局座標有誤

### ISSUE THREAD

**Issue by jiimmysu** [kiang/pharmacies#13]
您好：
小弟也有做個口罩地圖來玩玩，但接到有人來信說他附近的藥局位置有誤，似乎那種中文地址長得像連號的「89、91號」容易有問題，可以幫我修正資料上的座標嗎？謝謝。

快安藥局
https://kiang.github.io/pharmacies/#5931080148
正確座標 121.352382, 24.954769 
佐證資料 https://goo.gl/maps/GCug2EY2g12yhqKD9

同慶大藥局
https://kiang.github.io/pharmacies/#5932021643
正確座標 121.226650, 24.951139
佐證資料 https://goo.gl/maps/CLraFPvKqGxCd17MA

得康藥局
https://kiang.github.io/pharmacies/#5932022373
正確座標 121.229109, 24.946061
佐證資料 https://goo.gl/maps/NvLFJiheE4Q76ptPA

**Comment by kiang** [comment]
已經加入修正，感謝提供
