### ISSUE TITLE
藥局稱設備損壞並無販售口罩服務

### ISSUE THREAD

**Issue by silencesniper** [kiang/pharmacies#15]
如標題
https://kiang.github.io/pharmacies/#5903190513
這間藥局門口註寫「設備損壞無販售口罩服務」
所以不能買到口罩

**Comment by kiang** [comment]
在 c4cc1ca6ca4ec41b236b9794a19c26ddbd7d719e 加入了備註資訊，只是不知道藥局在設備修復後能否更新狀態

**Comment by kiang** [comment]
看起來該藥局已經從健保署清單中移除
