### ISSUE TITLE
新增台中市南屯區政豐大愛藥局

### ISSUE THREAD

**Issue by cheneric0929** [kiang/pharmacies#20]
台中市南屯區政豐大愛藥局沒有在地圖上顯示，在健保局查詢的連結如下
[https://www.nhi.gov.tw/QueryN/Query3_Detail.aspx?Page=3&HospID=5917072242](https://www.nhi.gov.tw/QueryN/Query3_Detail.aspx?Page=3&HospID=5917072242)

座標應為
大愛藥局(大業店)
No. 145-147號大業路南屯區台中市408
24.153553, 120.651540

**Comment by kiang** [comment]
已經修正，感謝提供

https://kiang.github.io/pharmacies/#5917072242
