### ISSUE TITLE
新增台中市南屯區方昇藥局

### ISSUE THREAD

**Issue by cheneric0929** [kiang/pharmacies#21]
台中市南屯區政方昇藥局沒有在地圖上顯示，在健保局查詢的連結如下
https://www.nhi.gov.tw/QueryN/Query3_Detail.aspx?Page=3&HospID=5903280601

座標應為
方昇藥局
408台中市南屯區大墩路813號
24.155145, 120.649530

**Comment by kiang** [comment]
已經修正，感謝提供

https://kiang.github.io/pharmacies/#5903280601
