### ISSUE TITLE
板橋快安藥局已無販售

### ISSUE THREAD

**Issue by towaawot** [kiang/pharmacies#22]
地址：新北市板橋區漢生西路31號1樓

家人到現場得知已無販售

**Comment by kiang** [comment]
目前系統只能夠依據庫存數字呈現，如果能夠可以請藥局進入健保署系統更新藥局的備註資訊，說明銷售情況，地圖端就會自動更新呈現備註資訊

https://kiang.github.io/pharmacies/#5931013843

**Comment by towaawot** [comment]
了解，謝謝。

**Comment by kiang** [comment]
資料已經移除

**Comment by towaawot** [comment]
感謝。都忘了這件事。

kiang <notifications@github.com> 於 2020年8月11日 週二 上午11:17寫道：
