### ISSUE TITLE
新增台中市大甲區健聖藥局 

### ISSUE THREAD

**Issue by cheneric0929** [kiang/pharmacies#24]
台中市大甲區健聖藥局沒有在地圖上顯示，在健保局查詢的連結如下
https://www.nhi.gov.tw/QueryN/Query3_Detail.aspx?Page=3&HospID=5936030077

座標應為
健聖藥局
437台中市大甲區通天路227號
24.381416, 120.653571

**Comment by kiang** [comment]
已經加入，感謝提供
