### ISSUE TITLE
新增台中市大甲區日南藥局 

### ISSUE THREAD

**Issue by cheneric0929** [kiang/pharmacies#25]
台中市大甲區日南藥局沒有在地圖上顯示，在健保局查詢的連結如下
https://www.nhi.gov.tw/QueryN/Query3_Detail.aspx?Page=3&HospID=5936031583

座標應為
日南藥局
437台中市大甲區通天路178之1號
24.381160, 120.654737

**Comment by kiang** [comment]
已經加入，感謝提供

**Comment by cheneric0929** [comment]
> 已經加入，感謝提供

它並沒有單獨列出，而是與 #24 顯示併在一起了

**Comment by kiang** [comment]
是的，同時處理兩個項目，這樣會有問題嗎？
https://kiang.github.io/pharmacies/#5936031583

**Comment by cheneric0929** [comment]
> 是的，同時處理兩個項目，這樣會有問題嗎？
> https://kiang.github.io/pharmacies/#5936031583

已正常，謝謝
