### ISSUE TITLE
新增苗栗縣頭份市惠祐藥局

### ISSUE THREAD

**Issue by cheneric0929** [kiang/pharmacies#33]
苗栗縣頭份市惠祐藥局沒有在地圖上顯示，在健保局查詢的連結如下
https://www.nhi.gov.tw/QueryN/Query3_Detail.aspx?Page=3&HospID=5935051867
座標應為
351台灣苗栗縣頭份市中正路165號
24.686933, 120.910109

**Comment by kiang** [comment]
已經修正，感謝提供，也許未來有興趣繼續協助修正的話，可以集中成單一案多筆資料即可

程式需要的欄位為醫事代碼與經緯度，像下面這樣
```
$ref['5903220150'] = array(120.679361,24.148036);
$ref['5901184437'] = array(121.518356,25.029544);
$ref['5901184473'] = array(121.515500,25.043557);
```
