### ISSUE TITLE
未發現此家藥局

### ISSUE THREAD

**Issue by silencesniper** [kiang/pharmacies#40]
https://kiang.github.io/pharmacies/#5903230085
我到那邊跟本連其他藥局影子都沒有，一堆住家。
這是某種魔法藥局，麻瓜看不到嗎QQ？

估狗地圖：https://www.google.com/maps/place/%E7%BF%94%E6%96%B0%E8%97%A5%E5%B1%80/@24.1477906,120.711598,3a,75y,281.52h,84.62t/data=!3m7!1e1!3m5!1snz0rpvBccjOkdSR7T9G8CA!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3Dnz0rpvBccjOkdSR7T9G8CA%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D308.7387%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656!4m5!3m4!1s0x34693d52d04ecb61:0x5307242b7637f20e!8m2!3d24.147835!4d120.711434

**Comment by kiang** [comment]
標示位置有問題，已經修正，但實際上也真的很不顯眼
https://goo.gl/maps/QBYQZaigikDjxZvt7
