### ISSUE TITLE
口罩數量與實際情形不符

### ISSUE THREAD

**Issue by gary780801** [kiang/pharmacies#41]
https://kiang.github.io/pharmacies/#5901024212
已經連續好幾周  口罩地圖顯示口罩數量很多
現場看已經貼出掛0通知

**Comment by kiang** [comment]
主要是藥局透過號碼牌銷售的關係，如果願意可以提醒藥局老闆進入健保署系統設定售完，這樣子口罩地圖就能夠正確顯示狀態

https://www.facebook.com/k.olc.tw/posts/1436822259824566
