### ISSUE TITLE
json/points.json 不再更新了

### ISSUE THREAD

**Issue by chelinchan24** [kiang/pharmacies#42]
您好：

我發現自 11 月 24 日起，[json/points.json](https://raw.githubusercontent.com/kiang/pharmacies/master/json/points.json) 已經不再更新了，時間停在當日早上 8 時 59 分。還煩請您再行檢查，謝謝您。

**Comment by kiang** [comment]
感謝提醒，已經修正，因為源頭的網址又改變了（嘆）

**Comment by chelinchan24** [comment]
謝謝您，辛苦了。
