### ISSUE TITLE
json/points.json 數量為 0

### ISSUE THREAD

**Issue by chelinchan24** [kiang/pharmacies#45]
您好：

我發現 json/points.json 中的口罩販售數量皆為 0，但經查詢[資料來源](https://data.gov.tw/dataset/116285)後，確定來源的口罩計數仍有持續更新，還煩請您再行檢查，謝謝您。

**Comment by kiang** [comment]
因為在藥局配售的政策已經停止，所以之前已經宣佈停止更新，後續除非政策有異動才會嘗試重啟更新程序，可以參考
https://link.medium.com/lrbN0wkTlmb

**Comment by chelinchan24** [comment]
您好：

藥局的實名制口罩仍有在持續販售，我今日也有親自去藥局購買，確認實名制是有在持續運作的。

不知是否存在誤會？謝謝您。

![IMG_0879](https://user-images.githubusercontent.com/16677586/147637235-be1700ba-9c08-453c-829c-d8ed4c716925.PNG)

**Comment by kiang** [comment]
我先試著重啟排程，改為每 5 分鐘更新一次，就先試試

**Comment by chelinchan24** [comment]
運作順利，相當感謝！
