### ISSUE TITLE
Points 0145080011 and 0291010010 are missing in point.json

### ISSUE THREAD

**Issue by lis186** [kiang/pharmacies#5]
Points 0145080011(衛生福利部花蓮醫院豐濱原住民分院) and 0291010010(連江縣立醫院) are in the raw data but missing in point.json

**Comment by kiang** [comment]
I used to add hospitals in the map. But one of them said the masks were only for internal use and requested to be removed. So I removed all hospitals.

Ref: https://m.facebook.com/story.php?story_fbid=1436822259824566&id=282921805214623

**Comment by lis186** [comment]
Ok, thanks.
