### ISSUE TITLE
緣來藥師藥局、日揚藥局、上全藥局GPS有誤

### ISSUE THREAD

**Issue by kai-tw** [kiang/pharmacies#7]
|醫事機構代碼|醫事機構名稱|經度,緯度|
|-|-|-|
|5931033176|緣來藥師藥局|121.518552,25.007578|
|5931101455|日揚藥局|121.461145,25.136232|
|5931100092|上全藥局|121.461358,25.136273|

這三間藥局經緯度經過 Google Map 檢查過了。

**Comment by kiang** [comment]
已經加入修正，感謝提供
